name: Linky
description: Sync Energy dashboards with your Linky smart meter
version: 1.1.0
slug: linky
init: false
url: https://github.com/bokub/ha-linky
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
homeassistant_api: true
options:
  consumption PRM: ''
  consumption token: ''
  consumption name: 'Linky consumption'
  consumption action: sync
schema:
  consumption PRM: str?
  consumption token: str?
  consumption name: str
  consumption action: list(sync|reset)
